---
# tasks file for db

- name: Install MySQL
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
  become: yes

- name: Start MySQL
  service:
    name: mysqld
    state: started
    enabled: yes
  become: yes

- name: Set root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    check_implicit_admin: true

- name: Create ~/.my.cnf file for creds
  template: src=my.cnf.j2 dest=/home/centos/.my.cnf

- name: Create Application Database
  mysql_db: 
    name: "{{ db_name }}"
    state: present

- name: Create Application DB User
  mysql_user: 
    name: "{{ db_user }}"
    password: "{{ db_user_password }}" 
    priv: '*.*:ALL' 
    host: '%' 
    state: present
