---
# tasks file for db

- name: Install MySQL
  apt:
    name: ['mysql-server', 'mysql-client', 'python-mysqldb', 'libmysqlclient-dev']
    state: present
    update_cache: yes
  become: yes

- name: Update all package
  apt:
    name: '*'
    state: latest
    update_cache: yes
  become: yes

- name: Set root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    state: present
    check_implicit_admin: true

- name: Create ~/.my.cnf file for creds
  template: src=my.cnf.j2 dest=/home/centos/.my.cnf

- name: Create Application Database
  mysql_db: 
    name: "{{ db_name }}"
    state: present

- name: Create Application DB User
  mysql_user: 
    name: "{{ db_user }}"
    password: "{{ db_user_password }}" 
    priv: '*.*:ALL' 
    host: '%' 
    state: present
