---
# tasks file for web
- name: Install Apache
  apt:
    name: ['apache2']
    state: present
  become: yes

- name: Start Apache
  service:
    name: apache2
    state: restarted
    enabled: yes
  become: yes
