---
# tasks file for common
- name: Update all packages
  apt:
    name: '*'
    state: latest
  become: yes

- name: Install PHP, PHP mod, & git.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - libapache2-mod-php 
    - php-mcrypt 
    - php-curl
    - php-xml
    - php-memcached
    - php-mysql
    - git
  become: yes